export const JOB_INTAKE_CONFIG = {
  roleFamilies: {
    AI_GENAI: [
      /\bai engineer\b/i,
      /\bapplied ai engineer\b/i,
      /\bgenai engineer\b/i,
      /\bllm engineer\b/i,
      /\bllm application engineer\b/i,
      /\bai application engineer\b/i,
      /\bml engineer\b/i,
      /\bmachine learning engineer\b/i,
      /\bml platform engineer\b/i,
      /\bmachine learning platform engineer\b/i,
    ],
    BACKEND_PLATFORM: [
      /\bbackend engineer\b/i,
      /\bbackend developer\b/i,
      /\bplatform engineer\b/i,
      /\bpython engineer\b/i,
      /\bpython developer\b/i,
      /\binfrastructure engineer\b/i,
      /\bapi engineer\b/i,
      /\bsoftware engineer, backend\b/i,
    ],
    SOFTWARE_GENERALIST: [
      /\bsoftware engineer\b/i,
      /\bsoftware developer\b/i,
      /\bapplication engineer\b/i,
      /\bfull[- ]stack engineer\b/i,
      /\bfull[- ]stack developer\b/i,
    ],
  },
  reviewTitlePatterns: [
    /\bdeveloper\b/i,
    /\bsoftware engineer\b/i,
    /\bapplication engineer\b/i,
    /\bfull[- ]stack\b/i,
  ],
  excludedTitlePatterns: [
    /\bvice president\b/i,
    /\bvp\b/i,
    /\bdirector\b/i,
    /\bprincipal\b/i,
    /\bstaff\b/i,
    /\bdistinguished\b/i,
    /\bfellow\b/i,
    /\bhead of\b/i,
    /\bengineering manager\b/i,
    /\bpeople manager\b/i,
    /\bmanager\b/i,
    /\barchitect\b/i,
  ],
  blockedKeywords: [
    'account executive',
    'business analyst',
    'customer success',
    'designer',
    'finance',
    'marketing',
    'product manager',
    'project manager',
    'recruiter',
    'sales',
    'support',
    'talent acquisition',
    'ux',
  ],
  preferredKeywords: [
    'agent',
    'agents',
    'ai',
    'anthropic',
    'api',
    'applied ai',
    'backend',
    'claude',
    'embeddings',
    'genai',
    'langchain',
    'llm',
    'machine learning',
    'ml platform',
    'openai',
    'platform',
    'prompt engineering',
    'python',
    'rag',
    'vector',
  ],
  earlyCareerPatterns: [
    /\bintern(ship)?\b/i,
    /\bjunior\b/i,
    /\bassociate\b/i,
    /\bearly career\b/i,
    /\bentry level\b/i,
    /\bnew grad\b/i,
  ],
  seniorPatterns: [
    /\bsenior\b/i,
    /\blead\b/i,
    /\bstaff\b/i,
    /\bprincipal\b/i,
    /\bdirector\b/i,
    /\bhead of\b/i,
    /\bvice president\b/i,
    /\bvp\b/i,
    /\bmanager\b/i,
    /\barchitect\b/i,
  ],
  experience: {
    maxAcceptYears: 5,
    maxReviewYears: 7,
  },
  freshness: {
    maxAcceptAgeDays: 7,
    maxReviewAgeDays: 14,
    staleAgeDays: 30,
    allowUnknownPostedAtAccept: false,
    allowUnknownOpenStatusAccept: false,
  },
  openStatus: {
    closedPhrases: [
      'closed',
      'expired',
      'inactive',
      'job removed',
      'no longer accepting applications',
      'position has been filled',
      'posting has expired',
      'this role is no longer available',
    ],
    openPhrases: [
      'accepting applications',
      'actively hiring',
      'apply now',
      'open role',
      'we are hiring',
    ],
  },
} as const;
